
export default function PostNewFeed() {
  return (
    <div>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
      <h1>new feed</h1>
    </div>
  );
}
