'use client';

import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import { ReactNode } from 'react';
import { store } from '@/store';
import { Provider } from 'react-redux';

config.autoAddCss = false;

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function App({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body className='bg-slate-800 text-slate-50'>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
